### GET request for books
GET http://localhost:4000/books
Accept: application/json
### // ⚫️⚫️☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰

### GET request to get book by {id}
GET http://localhost:4000/books/81
Content-Type: application/json
### // ⚫️⚫️☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰

### POST request to add book
POST http://localhost:4000/books
Content-Type: application/json

{
  "title": "New Book",
  "author": "AliasOne11",
  "desc": "A book by me. The new beginning"
}
### // ⚫️⚫️☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰

### PUT request to update book by id
PUT http://localhost:4000/books/1
Content-Type: application/json

{
  "title": "Updated Book",
  "author": "New Jsin",
  "desc": "New description"
}
### // ⚫️⚫️☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰

### DELETE request book by {id}
DELETE http://localhost:4000/books/81
Content-Type: application/json
### // ⚫️⚫️☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰☰


